targets:
  $default:
    builders:
      freezed:
        enabled: true
        generate_for:
          exclude:
            - test
            - example
          include:
            - test/integration/*

builders:
  freezed:
    import: "package:freezed/builder.dart"
    builder_factories: ["freezed"]
    build_extensions: { ".dart": [".g.part"] }
    auto_apply: dependents
    build_to: cache
    applies_builders: ['source_gen|combining_builder']
