targets:
  $default:
    builders:
      immutable:
        enabled: true
        generate_for:
          exclude:
            - test/*
          include:
            - example/lib/*
            - test/integration/*

builders:
  immutable:
    import: "package:immutable/builder.dart"
    builder_factories: ["immutable"]
    build_extensions: { ".dart": [".g.part"] }
    auto_apply: dependents
    build_to: cache
    applies_builders: ['source_gen|combining_builder']
