name: freezed
description: >
  Code generation for immutable classes that has a simple syntax/API without
  compromising on the features.
version: 0.0.0
homepage: https://github.com/rrousselGit/copy_with
authors:
  - Remi Rousselet <darky12s@gmail.com>

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  analyzer: ^0.39.0
  build: ">=0.12.6 <2.0.0"
  build_config: ">=0.2.6 <0.5.0"
  meta: ^1.1.0
  path: ^1.3.2
  source_gen: ^0.9.0

dev_dependencies:
  build_test:
  build_runner: ^1.0.0
  build_verify: ^1.1.0
  build_web_compilers: ">=1.0.0 <3.0.0"
  collection: ^1.14.0
  dart_style: ^1.2.0
  logging: ^0.11.3+1
  pub_semver: ^1.4.0
  source_gen_test: ^0.1.0
  test: ^1.6.0
  yaml: ^2.1.13
  matcher:
